ALTER SESSION SET "_oracle_script"=true;

CREATE USER JARDINERIA IDENTIFIED BY JARDINERIA;

ALTER USER JARDINERIA DEFAULT TABLESPACE USERS
              QUOTA UNLIMITED ON USERS;

ALTER USER JARDINERIA TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO JARDINERIA;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO JARDINERIA;