-- ADMINISTRADOR QUE ORTOGA PERMISOS AL USUARO1

ALTER SESSION SET "_oracle_script"=true;

CREATE USER User1 IDENTIFIED BY newuser;

GRANT CREATE SESSION to User1 WITH ADMIN OPTION;
 
GRANT CREATE TABLE to User1;

GRANT CREATE TABLESPACE to User1;

GRANT UNLIMITED TABLESPACE to User1;

GRANT CREATE USER to User1;

