-- ADMINISTRA AL USUARIO USUARIO2

ALTER SESSION SET "_oracle_script"=true;

CREATE USER User2 IDENTIFIED BY newpasante;

-- GRANT CREATE SESSION, CREATE TABLE to User2;
GRANT CREATE SESSION to User2;

SELECT * FROM regions;

-- Agregar permisos
GRANT SELECT ON REGIONS TO User2;
-- Quita permisos
REVOKE SELECT ON REGIONS FROM User2;